# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CatastroHistoria
                                 A QGIS plugin
 Catálogo completo de servicios disponibles a través de la Infraestructura de Datos Espaciales de España (IDEE).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-27
        copyright            : (C) 2023 by Laura García de Marina Vázquez
        email                : lauragarciademarina@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CatastroHistoria class from file CatastroHistoria.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Catastro_Historia import CatastroHistoria
    return CatastroHistoria(iface)
