# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CatastroHistoriaDock
                                 A QGIS plugin
 Catálogo completo de servicios disponibles a través de la Infraestructura de Datos Espaciales de España (IDEE).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-27
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Laura García de Marina Vázquez
        email                : lauragarciademarina@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from PyQt5 import QtCore, QtGui, QtWidgets
import os

class CatastroHistoriaDock(QtWidgets.QDialog):
    def __init__(self, parent=None):
        """Constructor."""
        super(CatastroHistoriaDock, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def setupUi(self, Split_Dock):
        self.setObjectName("Split_Dock")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.setFont(font)
        self.setWindowTitle("Catastro con Historia")
        self.verticalLayout = QtWidgets.QVBoxLayout(Split_Dock)
        self.verticalLayout.setObjectName("verticalLayout")
        
        """ TABS FOR EACH WEB SERVICE TYPE """
        self.tabs = QtWidgets.QTabWidget()
        self.WMS = QtWidgets.QWidget()
        self.WFS = QtWidgets.QWidget()
        self.tabs.addTab(self.WMS, 'WMS')
        self.tabs.addTab(self.WFS, 'WFS')
        self.verticalLayout.addWidget(self.tabs)


        """ WMS TAB """
        self.WMS.layout = QtWidgets.QVBoxLayout(self.WMS)
        self.WMS_gridLayout = QtWidgets.QGridLayout()
        self.WMS.layout.addLayout(self.WMS_gridLayout)
        self.organismo_lbl = QtWidgets.QLabel(self.WMS)
        self.organismo_lbl.setText('Organismo')
        self.organismo_lbl.adjustSize()
        self.WMS_gridLayout.addWidget(self.organismo_lbl, 0, 0, 1, 1)
        self.organismo_combobox = QtWidgets.QComboBox()
        self.WMS_gridLayout.addWidget(self.organismo_combobox, 0, 1, 1, 1)
        